<div class="container">
    <div class="left-column">
        <div class="customer_service">
            <h2 class="customer_service_title">Customer Service</h2>
            <p class="customer_service_desc">For delivery and after sales service</p>
            <a href="#" class="link">CLICK TO CREATE A NEW ENQUIRY &gt;</a>

        </div>
        <div class="customer_service">
            <h2 class="customer_service_title">Help Centre</h2>
            <p class="customer_service_desc">Need more information?</p>
            <a href="#" class="link">VISIT THE HELP CENTRE &gt;</a>

        </div>

        <h2 class="customer_service_title">General Enquiries & Feedback</h2>
        <p>Haven't found answers in our Help Centre? Send us your enquiry and a consultant will be in contact with you.
        </p>
        <div id="response-message"></div>
        <form class="enquiry-form">
            <input type="text" name="name" id="name" placeholder="Name*" required>
            <input type="email" name="email" id="email" placeholder="Email*" required>
            <input type="tel" name="phone_number" id="phone_number" placeholder="Phone number*" required>
            <input type="text" name="subject" id="subject" placeholder="Subject*" required>
            <textarea placeholder="Message" id="message" name="message" required></textarea>

            <button type="submit" id="submit-survey">SUBMIT</button>

            <p class="enquiry-form_desc">Please review our Privacy Policy which applies to all Personal Information
                collected, processed,
                or
                stored by King Living, including your Personal Information which we collect when you complete this form.
            </p>
        </form>

    </div>

    <div class="right-column">
        <h2 class="customer_service_title">Contact Us Directly</h2>
        <div class="right_customer_service">
            <div class="right_customer-img">
                <img src="<?= $block->getViewFileUrl('Mindarc_Survey::images/house.png') ?>" alt="Example Image" />
            </div>
            <div class="right_customer-content">
                <p class="right_desc">Locate your nearest King Living Showroom</p>
                <p>To talk to a representative at your closest showroom please click on the link below for their contact
                    details
                </p>
                <a href="#" class="link">FIND A SHOWROOM &gt;</a>
            </div>
        </div>
        <div class="right_customer_service">
            <div class="right_customer-img">
                <img src="<?= $block->getViewFileUrl('Mindarc_Survey::images/spanner.png') ?>" alt="Example Image" />
            </div>
            <div class="right_customer-content">
                <p class="right_desc">Customer Service</p>
                <p class="right_heading">Help Centre: <a class="right_link"
                        href="mailto:help@kingliving.com">help@kingliving.com</a></p>
                <p class="right_heading">Phone: +1 833 546 4548</p>
                <a href="#" class="right_link">Create a new Customer Service enquiry</a>
            </div>
        </div>
        <div class="right_customer_service">
            <div class="right_customer-img">
                <img class="fabric1" src="<?= $block->getViewFileUrl('Mindarc_Survey::images/fabric1.png') ?>"
                    alt="Example Image" />
            </div>
            <div class="right_customer-content">
                <p class="right_desc">Recovering & Refurbishment</p>
                <p>For enquiries on recovering, refurbishing, and professional cleaning please use the quote links
                    below.
                    For
                    all other after-sales support enquiries please contact the Customer Service team.</p>
                <a href="#" class="link">Get a quote for Recovering or Inserts</a>
            </div>
        </div>
        <div class="right_customer_service">
            <div class="right_customer-img">
                <img src="<?= $block->getViewFileUrl('Mindarc_Survey::images/sp.png') ?>" alt="Example Image" />
            </div>
            <div class="right_customer-content">
                <p class="right_desc">Media Enquiries</p>
                <p>For all media enquiries please <a href="#">click here</a>.</p>
            </div>
        </div>
    </div>
</div>